Repository dvilelaf/meme-ooorr, pull requests merged in 2025-03, with the labels that each got.

#185 Fix KeyError in get_packages method
  packages/dvilela/agents/memeooorr/aea-config.yaml
  packages/dvilela/services/memeooorr/service.yaml
  packages/dvilela/skills/memeooorr_abci/behaviour_classes/base.py
  packages/dvilela/skills/memeooorr_abci/skill.yaml
  packages/dvilela/skills/memeooorr_chained_abci/skill.yaml
  packages/packages.json
Labels: fix

#173 Feat/mech integration
  .gitleaksignore
  packages/dvilela/agents/memeooorr/aea-config.yaml
  packages/dvilela/connections/twikit/connection.py
  packages/dvilela/connections/twikit/connection.yaml
  packages/dvilela/services/memeooorr/service.yaml
  packages/dvilela/skills/memeooorr_abci/behaviour_classes/chain.py
  packages/dvilela/skills/memeooorr_abci/behaviour_classes/db.py
  packages/dvilela/skills/memeooorr_abci/behaviour_classes/mech.py
  packages/dvilela/skills/memeooorr_abci/behaviour_classes/twitter.py
  packages/dvilela/skills/memeooorr_abci/behaviours.py
  packages/dvilela/skills/memeooorr_abci/fsm_specification.yaml
  packages/dvilela/skills/memeooorr_abci/models.py
  packages/dvilela/skills/memeooorr_abci/payloads.py
  packages/dvilela/skills/memeooorr_abci/prompts.py
  packages/dvilela/skills/memeooorr_abci/rounds.py
  packages/dvilela/skills/memeooorr_abci/rounds_info.py
  packages/dvilela/skills/memeooorr_abci/skill.yaml
  packages/dvilela/skills/memeooorr_chained_abci/behaviours.py
  packages/dvilela/skills/memeooorr_chained_abci/composition.py
  packages/dvilela/skills/memeooorr_chained_abci/fsm_specification.yaml
  packages/dvilela/skills/memeooorr_chained_abci/models.py
  packages/dvilela/skills/memeooorr_chained_abci/skill.yaml
  packages/packages.json
  poetry.lock
  sample.env
  scripts/test_prompts_tools.py
Labels: enhancement

#188 Fix/fireworks key
  packages/dvilela/agents/memeooorr/aea-config.yaml
  packages/dvilela/services/memeooorr/service.yaml
  packages/dvilela/skills/memeooorr_abci/behaviour_classes/base.py
  packages/dvilela/skills/memeooorr_abci/models.py
  packages/dvilela/skills/memeooorr_abci/skill.yaml
  packages/dvilela/skills/memeooorr_chained_abci/skill.yaml
  packages/packages.json
  scripts/test_openai.py
Labels: bug, fix
